name: Python App Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Check files
        run: ls -la

      - name: Check Python version
        run: python --version

      - name: Run Python application
        run: python app.py
      - name: Print secret value
        run: echo "My name is :${{ secrets.MY_NAME}}"


